version: '2.1'

services:
  erstock-pos:
    image: erstock-pos
    container_name: erstock-pos
    build: . 
    environment:
      APP_ID: erstock-pos
      NODE_ENV: development
      NODE_PORT: "3031"
      Mongo_Ip: "10.0.8.223:27017"
      Erdis_Kafka_IP: "10.0.8.223:9092"
      Mongo_User: erdisAdmin:Erdis123*
      Mongo_Db: "ErstockPos"
    ports:
      - 3035:3035
      - "9235:9235"
    external_links:
      - erdis-mongo
    extra_hosts:
      - "SERVERTR149:10.0.8.149"
      - "SERVERTR146:10.0.8.146"
      - "SERVERTR13:192.168.0.13"
    networks: 
      - erdis
networks:
  erdis:
    external: true